### PR TITLE
Generate grid with fake sponsors according to arbitrarily-disgnated t…

### PR DESCRIPTION
**Pull request by allthesignals**
…est tiers

Repurposes tile-adapter to generate tiles based on the specs for placing sponsors randomly within their designated tiers.

### CODE REVIEW

**Comment by allthesignals** [comment]
@spencer15 do you hate it 😂

**Comment by allthesignals** [comment]
@spencer516 do you hate it 😂

**Comment by spencer516** [comment]
I love that you're using @ksin 's Ember Bingo as the base for this. 

(Hi Ken!)

**Comment by allthesignals** [comment]
> I love that you're using @ksin 's Ember Bingo as the base for this.
> 
> (Hi Ken!)

I was about to upgrade it to the latest Ember without a single issue! Thanks, @ksin!

**Pull request merged**
